version: "3"

services:
  challenge-cleanarch:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
      - "50051:50051"
      - "8282:8282"
    platform: linux/amd64
    networks:
      - challenge-cleanarch-network
      - rabbitmq-network
    depends_on:
      rabbitmq:
        condition: service_healthy
      database-challenge-cleanarch:
        condition: service_started
    env_file:
      - .env

  database-challenge-cleanarch:
    image: postgres:14.1
    container_name: database-challenge-cleanarch-container
    platform: linux/amd64
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    networks:
      - challenge-cleanarch-network

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    networks:
      - rabbitmq-network
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}

networks:
  challenge-cleanarch-network:
    driver: bridge

  rabbitmq-network:
    driver: bridge

volumes:
  database-challenge-cleanarch:
